# docker-compose.yml
version: "3"
services:
    napcat:
        environment:
            - ACCOUNT=${ACCOUNT}
            - WS_ENABLE=true
            - NAPCAT_UID=${NAPCAT_UID}
            - NAPCAT_GID=${NAPCAT_GID}
        ports:
            - 3001:3001
        container_name: napcat
        network_mode: bridge
        volumes:
            - ./data/QQ:/app/.config/QQ
            - ./data/config:/app/napcat/config
        restart: unless-stopped
        image: mlikiowa/napcat-docker:latest
