# docker-compose.yml
version: "3"
services:
    napcat:
        image: mlikiowa/napcat-docker:latest
        environment:
            - ACCOUNT=${ACCOUNT}
            - WS_ENABLE=true
            - NAPCAT_UID=${NAPCAT_UID}
            - NAPCAT_GID=${NAPCAT_GID}
        container_name: napcat
        volumes:
            - ./data/QQ:/app/.config/QQ
            - ./data/config:/app/napcat/config
        # ports:
        #     - 3001:3001
        # network_mode: bridge
        restart: unless-stopped
    qqbot:
        image: humxc/qqbot
        container_name: qqbot
        environment:
            - ONEBOT_ADDR=napcat:3001
            - SAUCENAO_APIKEY=${SAUCENAO_APIKEY}
